### ISSUE TITLE
add alternative to support torch.stft in RPi(aarch64)

### ISSUE THREAD

**Issue by BrownsugarZeer** [KumaTea/pytorch-aarch64#11]
# First

Thank you for building these lifesavers :D\
I found that someone posted a same [issue#6](https://github.com/KumaTea/pytorch-aarch64/issues/6), and also noticed that fixed in [#60976](https://github.com/pytorch/pytorch/pull//60976) with third-party then merged into lastest pytorch version [(here)](https://github.com/pytorch/pytorch/issues//62723#issuecomment-892783744) few days ago.

For now, I still faced the same problem about MKL(the following for more details). The first thing I tried to do was building from source, but it was my first time to build and everything was so strange to me :(\
Could you help me to check whether works on RPi4?\
Thanks a lot!!!

# Bug

`fft: ATen not compiled with MKL support`\
RuntimeError raised when trying to compute STFT on RPi4.

# To Reproduce

My code

```python
import os
import torch
import torchaudio
from speechbrain.pretrained import EncoderClassifier

classifier = EncoderClassifier.from_hparams(
    source="pretrained_model/best_model",
    hparams_file='xvector_interface.yaml',
    savedir="pretrained_model/best_model"
)

print(os.uname().machine)
print(torch.__version__)

# Perform classification
audio_file = '/home/sugar/Desktop/vscode_workspace/ASR/repos/GSC10/pretrained_model/022cd682_nohash_0.wav'
signal, fs = torchaudio.load(audio_file)  # id: 022cd682, lb: yes
output_probs, score, index, text_lab = classifier.classify_batch(signal)
print(output_probs, score, index, text_lab)
print('Target: 022cd682_yes, Predicted: ' + text_lab[0])
```

Error trace:

```
aarch64
1.9.0
Traceback (most recent call last):
  File "/home/sugar/Desktop/vscode_workspace/ASR/repos/GSC10/pretrained_model/train_interface.py", line 18, in <module>
    output_probs, score, index, text_lab = classifier.classify_batch(signal)
  File "/home/sugar/Desktop/vscode_workspace/ASR/repos/speechbrain/speechbrain/pretrained/interfaces.py", line 608, in classify_batch
    emb = self.encode_batch(wavs, wav_lens)
  File "/home/sugar/Desktop/vscode_workspace/ASR/repos/speechbrain/speechbrain/pretrained/interfaces.py", line 570, in encode_batch
    feats = self.modules.compute_features(wavs)
  File "/home/sugar/Desktop/vscode_workspace/ASR/repos/asr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sugar/Desktop/vscode_workspace/ASR/repos/speechbrain/speechbrain/lobes/features.py", line 136, in forward
    STFT = self.compute_STFT(wav)
  File "/home/sugar/Desktop/vscode_workspace/ASR/repos/asr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sugar/Desktop/vscode_workspace/ASR/repos/speechbrain/speechbrain/processing/features.py", line 161, in forward
    stft = torch.stft(
  File "/home/sugar/Desktop/vscode_workspace/ASR/repos/asr/lib/python3.9/site-packages/torch/functional.py", line 471, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: fft: ATen not compiled with MKL support
```

---

Simple sample:

```python
import os
import torch
print(os.uname().machine)
print(torch.__version__)
print(torch.fft.fft(torch.randn(3,3)))
```

Error trace:

```
aarch64
1.9.0
Traceback (most recent call last):
  File "/home/sugar/Desktop/vscode_workspace/ASR/repos/mkl_error/simple_sample.py", line 11, in <module>
    main()
  File "/home/sugar/Desktop/vscode_workspace/ASR/repos/mkl_error/simple_sample.py", line 7, in main
    print(torch.fft.fft(torch.randn(3, 3)))
RuntimeError: fft: ATen not compiled with MKL support
```

# Expected behavior

Everything run successfully.

# Environment

PyTorch version: 1.9.0\
OS: Ubuntu 21.04 64bit\
Python version: 3.9.5

**Comment by KumaTea** [comment]
Hi.

Still unable to solve the error, but I just realized that since `breakpad` is an error reporting tool and is newly add in PyTorch, simply disabling it (`export USE_BREAKPAD=0`) should be okay.

By this way I've managed to build the wheel of `v1.10.0a0`:

[torch-1.10.0a0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl](https://kumas3.s3.amazonaws.com/torch-1.10.0a0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl)

[torch-1.10.0a0-cp39-cp39-linux_aarch64.whl](https://kumas3.s3.amazonaws.com/torch-1.10.0a0-cp39-cp39-linux_aarch64.whl)

<details>
  <summary>details...</summary>
  GitHub won't allow me to upload `whl` here, so I have uploaded to AWS S3 instead. The link will live for about 1 month.
</details>

```
Python 3.9.6 (default, Aug 26 2021, 06:38:01)
[GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import torch
>>> print(os.uname().machine)
aarch64
>>> print(torch.__version__)
1.10.0a0
>>> print(torch.fft.fft(torch.randn(3,3)))
tensor([[-0.4325+0.0000j, -0.0342-0.3125j, -0.0342+0.3125j],
        [ 0.1138+0.0000j, -2.5345-0.4279j, -2.5345+0.4279j],
        [ 3.2972+0.0000j,  0.4888-1.5191j,  0.4888+1.5191j]])
```

**Comment by BrownsugarZeer** [comment]
Hi, I had already installed and it worked!!!

But unfortunately, there was another problem happened. I'm not sure that `torchaudio` should be also built as latest version or what. Since the latest ver. of `torch` and `torchaudio` are still under developing(perhaps there are more uncertain errors).

```
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.fft.fft(torch.randn(3, 3))
tensor([[ 1.6230+0.0000j, -0.5391+0.9954j, -0.5391-0.9954j],
        [-1.5692+0.0000j,  2.3500+0.4336j,  2.3500-0.4336j],
        [ 0.4668+0.0000j, -1.4437+1.2189j, -1.4437-1.2189j]])
>>> 
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sugar/test/test/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension  # noqa: F401
  File "/home/sugar/test/test/lib/python3.9/site-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/home/sugar/test/test/lib/python3.9/site-packages/torchaudio/extension/extension.py", line 11, in _init_extension
    _init_script_module(ext)
  File "/home/sugar/test/test/lib/python3.9/site-packages/torchaudio/extension/extension.py", line 19, in _init_script_module
    torch.classes.load_library(path)
  File "/home/sugar/test/test/lib/python3.9/site-packages/torch/_classes.py", line 48, in load_library
    torch.ops.load_library(path)
  File "/home/sugar/test/test/lib/python3.9/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/sugar/test/test/lib/python3.9/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZNK2at6Tensor9index_putERKN3c104ListINS1_8optionalIS0_EEEERKS0_b
>>> 
```

It's my personal project and I don't want to bother you too much.
But if you have any ideas, please let me know.

Thanks again, sincerely.

**Comment by KumaTea** [comment]
Hi, just as you expected, all secondary packages (torchaudio, vision, text, etc.) require a specific PyTorch version.

In your situation `torchaudio` is built on top of PyTorch v1.9.0, so it won't work on v1.10.0 unless recompiled.

**Comment by BrownsugarZeer** [comment]
Hi, I have a great news!!!
After installed some dependencies and ninja, I ran the script in `pytorch-aarch64/build/manylinux/audio.sh` with a following command. The the wheel was built successfully.
```
bash audio.sh 1.10.0a0 master
```
(Although faced some problems, and finally realized that I needed a RPi4 with 8G RAM. maybe you can mention this on the README)

In short, here is the result and works well !!

code:
```python
import os 
import torch
import torchaudio
from speechbrain.pretrained import EncoderClassifier

classifier = EncoderClassifier.from_hparams(
    source="/home/sugar/Desktop/vscode_workspace/ASR/repos/GSC10/pretrained_model/best_model",
    hparams_file='xvector_interface.yaml',
    savedir="/home/sugar/Desktop/vscode_workspace/ASR/repos/GSC10/pretrained_model/best_model"
)

print(os.uname().machine)
print(torch.__version__)
print(torchaudio.__version__)

# Perform classification
audio_file = '/home/sugar/Desktop/vscode_workspace/ASR/repos/GSC10/pretrained_model/022cd682_nohash_0.wav'
signal, fs = torchaudio.load(audio_file)  # id: 022cd682, lb: yes
output_probs, score, index, text_lab = classifier.classify_batch(signal)
print('Target: 022cd682_yes, Predicted: ' + text_lab[0])
```
result
```
aarch64
1.10.0a0
1.10.0a0
Target: 022cd682_yes, Predicted: yes
```

**Comment by KumaTea** [comment]
Hi, great to hear that!

> (Although faced some problems, and finally realized that I needed a RPi4 with 8G RAM. maybe you can mention this on the README)

You may try using `zram` to extend your RAM.

**Comment by hk0901** [comment]
Hello,  I've met the question as you too when use stft in torch 1.7.1 。But compile failed using torch-1.10.0a0, My gcc version is  7.3.0  。

I try to compile libtorch many times in my own machine but failed at last ! Can you provide a solved version of torch1.7.1?  
Thanks a lot

![image](https://user-images.githubusercontent.com/53263206/132289201-b9e1dbd3-b55c-40fe-9966-6b37ac9dd484.png)


![image](https://user-images.githubusercontent.com/53263206/132289138-842d73fb-7145-423b-be15-04b345152e5e.png)

**Comment by KumaTea** [comment]
Hi @hk0901 ,

> Can you provide a solved version of torch1.7.1?

I'm afraid I can't, because MKL support for aarch64 will be added since 1.10, patching older versions is likely not feasible.

> But compile failed using torch-1.10.0a0, My gcc version is 7.3.0

Although [GCC 5 should be able to support C++14](https://en.cppreference.com/w/cpp/compiler_support/14) which is needed by PyTorch, you might need gcc 8 or newer based on my experience. [It might be okay to use a newer gcc version.](https://stackoverflow.com/a/32662709/10714490)

**Comment by hk0901** [comment]
你好， torch-1.10.0a0-cp39-cp39-linux_aarch64.whl 的运行结果好像不正确， 我在x64平台的master版本，arm的1.9.0的版本，得到的结果都是相同，但是你的这个whl模型输出结果和stft的结果都和他们不一样， 请问是哪里有问题吗

另外，我自己编译总是报错，所以希望能用您提供的arm版本最新的pytorch
![image](https://user-images.githubusercontent.com/53263206/132530383-7c96af68-d89b-4b85-b985-7932afaab1d9.png)

**Comment by KumaTea** [comment]
> 但是你的这个whl模型输出结果和stft的结果都和他们不一样

我没有用过 `stft` 算法，不甚清楚具体原因，或许可以提供下实例代码和运行结果

> 自己编译总是报错

**`armv8.2-a+dotprod`** 要求 [GCC 版本在 **8.1** 以上](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/architecture-support#:~:text=Dot%20Product%20extension)
